/**
 * Excel Report Export Module
 *
 * Generates Excel spreadsheets for TGO carbon analysis
 * Supports multiple worksheets, charts, and Thai language
 */

import * as XLSX from 'xlsx';
import type { Report, ReportSection, TableData, ChartData } from './types';

// ============================================
// Excel Configuration
// ============================================

interface ExcelStyle {
  headerFill: string;
  headerFont: string;
  alternateRowFill: string;
}

const EXCEL_STYLES: ExcelStyle = {
  headerFill: '10B981', // Emerald-500
  headerFont: 'FFFFFF',
  alternateRowFill: 'F3F4F6', // Gray-100
};

// ============================================
// Excel Generator
// ============================================

export class ExcelReportGenerator {
  private workbook: XLSX.WorkBook;

  constructor() {
    this.workbook = XLSX.utils.book_new();
  }

  /**
   * Generate Excel workbook from Report object
   */
  generate(report: Report): Blob {
    // Summary worksheet
    this.addSummarySheet(report);

    // Section worksheets
    for (const section of report.sections) {
      this.addSectionSheet(section);
    }

    // Data tables worksheet
    this.addDataTablesSheet(report);

    // Recommendations worksheet
    this.addRecommendationsSheet(report);

    // Generate buffer and blob
    const buffer = XLSX.write(this.workbook, { type: 'array', bookType: 'xlsx' });
    return new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
  }

  /**
   * Add summary worksheet
   */
  private addSummarySheet(report: Report): void {
    const data: Array<Array<string | number>> = [];

    // Header
    data.push(['Report Summary']);
    data.push([]);

    // Report info
    data.push(['Report Type:', report.type.toUpperCase()]);
    data.push(['Title:', report.title.replace('\n', ' - ')]);
    data.push(['Model:', report.modelName]);
    data.push(['Generated:', report.generatedAt.toISOString()]);
    data.push(['Status:', report.status.toUpperCase()]);
    data.push([]);

    // Key Findings
    data.push(['Key Findings']);
    data.push(['-'.repeat(50)]);
    for (const finding of report.summary.keyFindings) {
      data.push([finding]);
    }
    data.push([]);

    // Metrics
    data.push(['Metrics']);
    data.push(['-'.repeat(50)]);
    data.push(['Critical Issues:', report.summary.criticalIssues]);
    data.push(['Warnings:', report.summary.warnings]);
    if (report.summary.overallScore !== undefined) {
      data.push(['Overall Score:', report.summary.overallScore]);
    }
    if (report.summary.complianceStatus) {
      data.push(['Compliance Status:', report.summary.complianceStatus.toUpperCase()]);
    }
    data.push([]);

    // Metadata
    data.push(['Metadata']);
    data.push(['-'.repeat(50)]);
    data.push(['Generated By:', report.metadata.generatedBy]);
    data.push(['Version:', report.metadata.version]);
    data.push(['Analysis Depth:', report.metadata.analysisDepth]);
    data.push(['Processing Time:', `${report.metadata.processingTimeMs}ms`]);

    const ws = XLSX.utils.aoa_to_sheet(data);

    // Set column widths
    ws['!cols'] = [{ wch: 20 }, { wch: 60 }];

    XLSX.utils.book_append_sheet(this.workbook, ws, 'Summary');
  }

  /**
   * Add section worksheet
   */
  private addSectionSheet(section: ReportSection): void {
    const data: Array<Array<string | number>> = [];

    // Section title
    data.push([section.title]);
    data.push([]);

    // Parse content into rows
    const lines = section.content.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();

      if (trimmed.startsWith('## ')) {
        data.push([]);
        data.push([trimmed.replace('## ', '').toUpperCase()]);
        data.push(['-'.repeat(50)]);
      } else if (trimmed.startsWith('### ')) {
        data.push([]);
        data.push([trimmed.replace('### ', '')]);
      } else if (trimmed.startsWith('| ') && trimmed.endsWith(' |')) {
        // Parse markdown table row
        const cells = trimmed
          .split('|')
          .filter(cell => cell.trim() !== '')
          .map(cell => cell.trim());
        if (!cells.every(c => c.match(/^-+$/))) {
          // Skip separator rows
          data.push(cells);
        }
      } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        data.push([`• ${trimmed.substring(2)}`]);
      } else if (trimmed === '---') {
        data.push([]);
      } else if (trimmed.length > 0 && !trimmed.startsWith('#') && !trimmed.startsWith('!')) {
        // Regular text
        data.push([trimmed.replace(/\*\*/g, '')]);
      }
    }

    // Sanitize sheet name (Excel has 31 char limit)
    const sheetName = this.sanitizeSheetName(section.title);
    const ws = XLSX.utils.aoa_to_sheet(data);

    // Set column widths
    ws['!cols'] = [{ wch: 30 }, { wch: 30 }, { wch: 20 }, { wch: 20 }];

    XLSX.utils.book_append_sheet(this.workbook, ws, sheetName);
  }

  /**
   * Add combined data tables worksheet
   */
  private addDataTablesSheet(report: Report): void {
    const data: Array<Array<string | number>> = [];

    data.push(['Data Tables']);
    data.push([]);

    // Collect all tables from sections
    for (const section of report.sections) {
      if (section.tables && section.tables.length > 0) {
        for (const table of section.tables) {
          this.addTableToData(data, table);
          data.push([]);
        }
      }

      // Also process charts as data tables
      if (section.charts && section.charts.length > 0) {
        for (const chart of section.charts) {
          this.addChartToData(data, chart);
          data.push([]);
        }
      }
    }

    if (data.length <= 2) {
      data.push(['No data tables available']);
    }

    const ws = XLSX.utils.aoa_to_sheet(data);
    ws['!cols'] = [{ wch: 40 }, { wch: 20 }, { wch: 15 }];

    XLSX.utils.book_append_sheet(this.workbook, ws, 'Data Tables');
  }

  /**
   * Add recommendations worksheet
   */
  private addRecommendationsSheet(report: Report): void {
    const data: Array<Array<string | number>> = [];

    data.push(['Recommendations']);
    data.push([]);

    data.push(['Priority', 'Recommendation', 'Estimated Impact']);
    data.push(['-'.repeat(10), '-'.repeat(50), '-'.repeat(20)]);

    report.summary.recommendations.forEach((rec, index) => {
      const priority = index < 3 ? 'High' : index < 6 ? 'Medium' : 'Low';
      data.push([priority, rec, 'TBD']);
    });

    data.push([]);
    data.push(['Action Items']);
    data.push(['-'.repeat(50)]);

    // Extract action items from report sections
    for (const section of report.sections) {
      if (section.title.toLowerCase().includes('recommend') ||
          section.title.toLowerCase().includes('action') ||
          section.title.toLowerCase().includes('ข้อเสนอแนะ')) {
        const lines = section.content.split('\n');
        for (const line of lines) {
          if (line.trim().match(/^\d+\.|^-|^\*/)) {
            data.push([line.trim().replace(/^[\d.-]*\s*/, '')]);
          }
        }
      }
    }

    const ws = XLSX.utils.aoa_to_sheet(data);
    ws['!cols'] = [{ wch: 15 }, { wch: 60 }, { wch: 20 }];

    XLSX.utils.book_append_sheet(this.workbook, ws, 'Recommendations');
  }

  /**
   * Add a table to data array
   */
  private addTableToData(data: Array<Array<string | number>>, table: TableData): void {
    data.push([table.title]);
    data.push(table.headers);

    for (const row of table.rows) {
      data.push(row);
    }
  }

  /**
   * Add chart data to data array
   */
  private addChartToData(data: Array<Array<string | number>>, chart: ChartData): void {
    data.push([chart.title]);
    data.push(['Label', 'Value', 'Percentage']);

    const total = chart.data.reduce((sum, d) => sum + d.value, 0);
    for (const item of chart.data) {
      const percentage = ((item.value / total) * 100).toFixed(1);
      data.push([item.label, item.value, `${percentage}%`]);
    }
  }

  /**
   * Sanitize sheet name for Excel (31 char limit, no special chars)
   */
  private sanitizeSheetName(name: string): string {
    return name
      .replace(/[\\/*?[\]:]/g, '')
      .substring(0, 31);
  }
}

// ============================================
// Export Functions
// ============================================

/**
 * Generate Excel workbook from Report object
 */
export function generateExcel(report: Report): Blob {
  const generator = new ExcelReportGenerator();
  return generator.generate(report);
}

/**
 * Download Excel report
 */
export function downloadExcel(report: Report, filename?: string): void {
  const blob = generateExcel(report);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `${report.type}-report-${Date.now()}.xlsx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate CSV from Report object (single sheet)
 */
export function generateCSV(report: Report): Blob {
  const data: Array<Array<string | number>> = [];

  // Header
  data.push(['Report', report.title.replace('\n', ' - ')]);
  data.push(['Type', report.type]);
  data.push(['Generated', report.generatedAt.toISOString()]);
  data.push([]);

  // Key findings
  data.push(['Key Findings']);
  for (const finding of report.summary.keyFindings) {
    data.push([finding]);
  }
  data.push([]);

  // Data from sections
  for (const section of report.sections) {
    data.push([section.title]);
    if (section.tables) {
      for (const table of section.tables) {
        data.push(table.headers);
        for (const row of table.rows) {
          data.push(row);
        }
        data.push([]);
      }
    }
  }

  const ws = XLSX.utils.aoa_to_sheet(data);
  const csv = XLSX.utils.sheet_to_csv(ws);
  return new Blob([csv], { type: 'text/csv;charset=utf-8;' });
}

/**
 * Download CSV report
 */
export function downloadCSV(report: Report, filename?: string): void {
  const blob = generateCSV(report);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `${report.type}-report-${Date.now()}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
