'use client';

/**
 * DocumentEditorPanel - Markdown Document Editor
 *
 * Features:
 * - Markdown editing with live preview
 * - Document templates (reports, certifications)
 * - Export to PDF/Word
 * - Generated by AI from chat
 *
 * Tambo-enabled: AI can update document content via natural language.
 */

import { useState, useCallback, useMemo } from 'react';
import Markdown from 'react-markdown';
import { useTranslation } from '@/i18n/provider';
import { FileText, Download, File, Eye, Edit3 } from 'lucide-react';
import { withTamboInteractable, type WithTamboInteractableProps } from '@tambo-ai/react';
import { DocumentEditorSchema, type DocumentEditorProps } from '@/lib/tambo/schemas';

/** Section type from schema */
type DocumentSection = NonNullable<DocumentEditorProps['sections']>[number];

/** Inner component that receives Tambo props */
function DocumentEditorPanelInner(props: DocumentEditorProps & WithTamboInteractableProps) {
  const { content, title, sections } = props;
  const { t } = useTranslation();
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState<string | null>(null);
  const [editedTitle, setEditedTitle] = useState<string | null>(null);

  // Compute the document content - either from sections or direct content
  const documentContent = useMemo(() => {
    if (sections && sections.length > 0) {
      // Build content from sections
      return sections
        .map((section: DocumentSection) => `## ${section.heading}\n\n${section.content}`)
        .join('\n\n');
    }
    return content || '';
  }, [content, sections]);

  // Current display values (edited or from props)
  const displayContent = editedContent ?? documentContent;
  const displayTitle = editedTitle ?? title ?? t('workspacePanel.untitledDocument');

  // Handle content changes in edit mode
  const handleContentChange = useCallback((newContent: string) => {
    setEditedContent(newContent);
  }, []);

  // Handle title changes
  const handleTitleChange = useCallback((newTitle: string) => {
    setEditedTitle(newTitle);
  }, []);

  // Export placeholder
  const handleExport = useCallback((format: 'pdf' | 'csv') => {
    // Export functionality - would be handled via Tambo tools or external service
    console.log(`Exporting document as ${format}`);
  }, []);

  // Check if we have any content to display
  const hasContent = displayContent.length > 0;

  return (
    <div data-testid="document-editor-panel" className="h-full w-full flex flex-col">
      {!hasContent ? (
        // Empty state
        <div className="flex flex-col items-center justify-center h-full text-center p-4">
          <FileText className="w-12 h-12 text-indigo-500 mb-4" />
          <h3 className="text-lg font-semibold mb-2">{t('workspacePanel.noDocumentLoaded')}</h3>
          <p className="text-sm text-neutral-600 dark:text-neutral-400 mb-4">
            {t('workspacePanel.askAiToGenerate')}
          </p>
          <div className="flex gap-2">
            <button className="px-3 py-1.5 text-sm bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 rounded hover:bg-indigo-200 dark:hover:bg-indigo-900/50">
              {t('workspacePanel.carbonReportTemplate')}
            </button>
            <button className="px-3 py-1.5 text-sm bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 rounded hover:bg-indigo-200 dark:hover:bg-indigo-900/50">
              {t('workspacePanel.boqSummaryTemplate')}
            </button>
          </div>
        </div>
      ) : (
        <>
          {/* Header */}
          <div className="flex items-center justify-between p-3 border-b border-neutral-200 dark:border-neutral-700 bg-white dark:bg-neutral-800">
            <div className="flex items-center gap-2">
              <File className="w-4 h-4 text-neutral-600 dark:text-neutral-400" />
              <input
                type="text"
                value={displayTitle}
                onChange={(e) => handleTitleChange(e.target.value)}
                className="text-sm font-medium bg-transparent border-none focus:outline-none focus:ring-2 focus:ring-indigo-500 rounded px-2 py-1"
              />
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => setIsEditing(!isEditing)}
                className="flex items-center gap-1.5 px-3 py-1 text-sm border border-neutral-300 dark:border-neutral-600 rounded hover:bg-neutral-100 dark:hover:bg-neutral-700"
                aria-pressed={isEditing}
              >
                {isEditing ? (
                  <>
                    <Eye className="w-3.5 h-3.5" />
                    {t('workspacePanel.preview')}
                  </>
                ) : (
                  <>
                    <Edit3 className="w-3.5 h-3.5" />
                    {t('workspacePanel.edit')}
                  </>
                )}
              </button>
              <button
                onClick={() => handleExport('pdf')}
                className="p-2 hover:bg-neutral-100 dark:hover:bg-neutral-700 rounded"
                title={t('workspacePanel.exportPDF')}
                aria-label={t('workspacePanel.exportAsPDF')}
              >
                <Download className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-auto p-4">
            {isEditing ? (
              // Edit mode
              <textarea
                value={displayContent}
                onChange={(e) => handleContentChange(e.target.value)}
                className="w-full h-full p-4 font-mono text-sm bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-700 rounded resize-none focus:outline-none focus:ring-2 focus:ring-indigo-500"
                placeholder={t('workspacePanel.writeMarkdown')}
                aria-label={t('workspacePanel.documentContentEditor')}
              />
            ) : (
              // Preview mode with Markdown rendering
              <article className="prose prose-sm dark:prose-invert max-w-none prose-headings:font-semibold prose-a:text-indigo-600 dark:prose-a:text-indigo-400">
                <Markdown>{displayContent}</Markdown>
              </article>
            )}
          </div>

          {/* Footer */}
          <div className="p-2 border-t border-neutral-200 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-800 text-xs text-neutral-600 dark:text-neutral-400">
            {sections && sections.length > 0 && (
              <span>
                {sections.length} {t('workspacePanel.sections')}
              </span>
            )}
          </div>
        </>
      )}
    </div>
  );
}

/** Tambo-wrapped interactable component */
export const DocumentEditorInteractable = withTamboInteractable(DocumentEditorPanelInner, {
  componentName: 'DocumentEditor',
  description: 'Markdown document editor for reports and documentation',
  propsSchema: DocumentEditorSchema,
});

/** Default export for panel usage */
export function DocumentEditorPanel(props: DocumentEditorProps) {
  return <DocumentEditorInteractable {...props} />;
}
