name = "carbon-bim-backend"
main = "worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Backend VM address (Dokploy)
BACKEND_HOST = "20.55.21.69"
BACKEND_PORT = "40"
